"""One-time, assertion-checked source edit on the feature branch; removed after application."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
def edit(name,old,new,count=1):
 p=root/name;s=p.read_text();assert s.count(old)==count,(name,s.count(old),old[:100]);p.write_text(s.replace(old,new))
cats=['招聘宣讲','线上宣传','经验分享','指导讲座','就业实践','专项活动','部门活动']
for name in ['app.js','team-ui.js','store.js','team-client.js']:
 p=root/'assets'/name;p.write_text("import './categories.js?v=2.2.1';\n"+p.read_text())
edit('assets/app.js',"const categories = ['部门工作','会议培训','志愿服务','文体活动','交流分享','其他'];","const {values:categories,defaultValue:defaultCategory,normalize:normalizeCategory,isValid:isCategory,populate:populateCategories}=globalThis.ActivityCategories;")
edit('assets/app.js',"const categoryColors = [['#efe7f6','#987eaf'],['#e8edf7','#8495b5'],['#e7eee4','#8c9e7a'],['#f3e6e6','#b38b92'],['#f2ebdf','#b19a76'],['#ece8ee','#998ca4']];","const categoryColors = [['#e8edf7','#8495b5'],['#e6edf2','#7c9cad'],['#f2ebdf','#b19a76'],['#efe7f6','#987eaf'],['#e7eee4','#8c9e7a'],['#f3e6e6','#b38b92'],['#ece8ee','#998ca4']];")
edit('assets/app.js','function chip(category){const i=Math.max(0,categories.indexOf(category)),[bg,color]=categoryColors[i];',"function chip(category){category=normalizeCategory(category)||('原分类：'+category);const i=Math.max(0,categories.indexOf(category)),[bg,color]=categoryColors[i];")
edit('assets/app.js','r.category===state.category','normalizeCategory(r.category)===state.category')
edit('assets/app.js','const cats=[...new Set([...categories,...data().map(r=>r.category)])];','const cats=categories;')
edit('assets/app.js'," if(r?.category&&!Array.from(form.elements.category.options).some(o=>o.value===r.category))form.elements.category.add(new Option(r.category,r.category));\n",'')
edit('assets/app.js',"k==='category'?'部门工作'","k==='category'?defaultCategory")
edit('assets/app.js',"form.elements.people.value=r?r.people.join('、'):'';","form.elements.people.value=r?r.people.join('、'):'';\n populateCategories(form.elements.category,r?.category??defaultCategory);")
edit('assets/app.js'," dirty=true;renderStaged();$('#form-status').textContent='已恢复暂存的信息与附件，尚未正式保存。';"," populateCategories($('#record-form').elements.category,d.fields?.category??defaultCategory);\n dirty=true;renderStaged();$('#form-status').textContent='已恢复暂存的信息与附件，尚未正式保存。';")
edit('assets/app.js'," e.preventDefault();if(processing||saving)return;const f=$('#record-form');if(!f.reportValidity())return;"," e.preventDefault();if(processing||saving)return;const f=$('#record-form');if(!f.reportValidity())return;\n if(!isCategory(f.elements.category.value)){toast('请从七项活动类型中选择一项。',true);return;}")
edit('index.html','<select name="category"><option>部门工作</option><option>会议培训</option><option>志愿服务</option><option>文体活动</option><option>交流分享</option><option>其他</option></select>','<select name="category" required="">'+''.join('<option'+(' selected=""' if c=='部门活动' else '')+'>'+c+'</option>' for c in cats)+'</select>')
edit('assets/excel-worker.js',"importScripts('./vendor/xlsx.full.min.js','./excel-core.js?v=2.1.0');","importScripts('./vendor/xlsx.full.min.js','./categories.js?v=2.2.1','./excel-core.js?v=2.2.1');")
edit('assets/excel-core.js',"(function(root){\n","(function(root){\n const coreFields=['title','date','work','people'];\n const types=()=>root.ActivityCategories;\n const categoryField=c=>['活动类型','活动分类','类型','分类'].includes(norm(c));\n")
edit('assets/excel-core.js',"category:'部门工作'","category:types()?.normalize(vals.category)||(text(vals.category)?'':(types()?.normalize(options.category)||'部门活动')),originalCategory:text(vals.category)")
edit('assets/excel-core.js',"records.push({sheet:sheet.name","const cat=text(vals.category);if(cat&&!types()?.normalize(cat))warnings.push('活动类型不在新七项分类中，请选择；原类型：'+cat);records.push({sheet:sheet.name")
edit('assets/excel-core.js',"include:!!(title&&work&&people&&parsed.date)","include:!!(title&&work&&people&&parsed.date&&(!cat||types()?.normalize(cat)))")
edit('assets/excel-core.js',"mapping=found;carry=","const ci=row.findIndex(categoryField);if(ci>=0)found.category=ci;mapping=found;carry=")
edit('assets/excel-core.js',"for(const k of ['title','date','work','people'])vals[k]","for(const k of [...coreFields,'category'])vals[k]")
edit('assets/excel-core.js',"if(!mapping&&field(row[0])&&row.length>=2){const k=field(row[0]);if(vertical[k])flushVertical(ri);vertical[k]=row[1];if(Object.keys(vertical).length===4)flushVertical(ri+1);continue;}","if(!mapping&&(field(row[0])||categoryField(row[0]))&&row.length>=2){const k=field(row[0])||'category';if(vertical[k])flushVertical(ri);vertical[k]=row[1];continue;}")
edit('assets/excel-core.js',"if(Object.keys(vertical).length>=3)add(vertical","if(coreFields.filter(k=>vertical[k]!==undefined).length>=3)add(vertical")
edit('assets/team-ui.js',"const $=(s,r=document)=>","const {values:categories,defaultValue:defaultCategory,normalize:normalizeCategory,isValid:isCategory}=globalThis.ActivityCategories;\nconst categoryOptions=value=>(isCategory(value)?'':'<option value=\"\" disabled selected>请选择活动类型</option>')+categories.map(c=>`<option value=\"${c}\" ${c===value?'selected':''}>${c}</option>`).join('');\nconst $=(s,r=document)=>")
edit('assets/team-ui.js','<label class="checkbox-label"><input id="excel-hidden"','<label>原表未填类型时归入<select id="excel-category">${categoryOptions(defaultCategory)}</select></label><label class="checkbox-label"><input id="excel-hidden"')
edit('assets/team-ui.js',"excelOptions.year=$('#excel-year').value;","excelOptions.category=$('#excel-category').value;excelOptions.year=$('#excel-year').value;")
edit('assets/team-ui.js',"const validRow=r=>!!(r.title?.trim()","const validRow=r=>!!(isCategory(r.category)&&r.title?.trim()")
edit('assets/team-ui.js','<th>参与具体工作</th><th>人员</th>','<th>参与具体工作</th><th>人员</th><th>活动类型</th>')
edit('assets/team-ui.js','aria-label="第 ${first+i+1} 条人员"></td></tr>','aria-label="第 ${first+i+1} 条人员"></td><td><select data-row-index="${first+i}" data-field="category" aria-label="第 ${first+i+1} 条活动类型" ${r.imported?\'disabled\':\'\'}>${categoryOptions(r.category)}</select></td></tr>')
edit('assets/team-ui.js',"category:r.category||'部门工作'","category:r.category")
edit('assets/team-ui.js',"async function rowToRecord(r){\n","async function rowToRecord(r){\n if(!isCategory(r.category))throw new Error('请先核对活动类型，必须从指定的七项中选择。');\n")
edit('assets/team-ui.js',"仍有日期或必填字段无效，请修正后再导入。","仍有日期、活动类型或必填字段无效，请修正后再导入。")
edit('assets/team-client.js',"category:f.category||'部门工作'","category:globalThis.ActivityCategories.normalize(f.category)||''")
edit('assets/store.js',"category:str(r.category,50) ? r.category : '其他'","category:str(r.category,50)&&r.category.trim() ? (globalThis.ActivityCategories.normalize(r.category)||r.category) : globalThis.ActivityCategories.defaultValue")
for before,after in {'部门工作':'部门活动','会议培训':'指导讲座','志愿服务':'专项活动','文体活动':'部门活动','交流分享':'经验分享'}.items():
 p=root/'assets/demo.js';p.write_text(p.read_text().replace("'"+before+"'","'"+after+"'"))
for p in list((root/'assets').glob('*.js'))+[root/'index.html']:
 p.write_text(re.sub(r'(\?v=|v|VERSION=\')2\.[12]\.0',r'\g<1>2.2.1',p.read_text()))
p=root/'package.json';j=json.loads(p.read_text());j['version']='2.2.1';j['scripts']['check']+=' && node --check assets/categories.js';j['scripts']['test']='node --test tests/core.test.mjs tests/categories.test.mjs';p.write_text(json.dumps(j,ensure_ascii=False,separators=(',',':'))+'\n')
edit('tests/ui-modes.py',"to_contain_text('v2.2.0')","to_contain_text('v2.2.1')")
edit('.github/workflows/pages.yml',"          python3 tests/ui-modes.py\n","          python3 tests/categories.py\n          python3 tests/ui-modes.py\n")
edit('.github/workflows/pages.yml','          python3 tests/ui-modes.py "$LIVE_URL"\n','          python3 tests/categories.py "$LIVE_URL"\n          python3 tests/ui-modes.py "$LIVE_URL"\n')
edit('.github/workflows/pages.yml','for asset in boot.js','for asset in categories.js boot.js')
edit('.github/workflows/pages.yml','v2.2.0','v2.2.1',2)
edit('.github/workflows/backup.yml','# v2.2.0:','# v2.2.1:')
edit('README.md','**v2.2.0 · 双界面、免登录共享版**','**v2.2.1 · 双界面、免登录共享版**')
edit('README.md','## 两套界面，同一份数据','## 活动类型\n\n统一按顺序提供：招聘宣讲、线上宣传、经验分享、指导讲座、就业实践、专项活动、部门活动。新增、编辑、筛选、草稿恢复与 Excel 导入共用 `assets/categories.js`。新记录默认部门活动；Excel 原表没有类型时可设置缺省类型，导入前也可逐条修正。表内明确有效类型会保留，未知类型提示人工选择，不凭活动名称猜测。\n\n所有示例记录与原附件保留，仅更新分类标签。两套 UI、透明校徽、图片引擎及免登录共享不改动。\n\n## 两套界面，同一份数据')
print('Category settings applied. Existing UI styles, images and storage endpoints unchanged.')
