"""One-time guarded source edit on the category feature branch; no record/database writes."""
from pathlib import Path
p=Path(__file__).resolve().parents[1]
def replace(path, old, new, count=1):
 f=p/path;s=f.read_text();assert s.count(old)==count,(path,old[:70],s.count(old));f.write_text(s.replace(old,new))
replace('assets/app.js',"import {team} from './team-client.js?v=2.1.0';", "import {CATEGORY_OPTIONS,DEFAULT_CATEGORY,setCategoryField,readCategoryField,updateCategoryVisibility,suggestCustomCategories} from './categories.js?v=2.2.1';\nimport {team} from './team-client.js?v=2.1.0';")
replace('assets/app.js',"'./team-ui.js?v=2.1.0'", "'./team-ui.js?v=2.2.1'")
replace('assets/app.js',"const categories = ['部门工作','会议培训','志愿服务','文体活动','交流分享','其他'];", 'const categories = CATEGORY_OPTIONS;')
replace('assets/app.js',"['#ece8ee','#998ca4']];", "['#e3edf0','#7598a4'],['#ece4f7','#937db1'],['#ece8ee','#998ca4']];")
replace('assets/app.js',"const i=Math.max(0,categories.indexOf(category)),[bg,color]=categoryColors[i];", "const i=categories.indexOf(category),[bg,color]=categoryColors[i<0?categoryColors.length-1:i];")
replace('assets/app.js',"style=\"--chip-bg:${bg};--chip-color:${color}\"", "title=\"${esc(category)}\" style=\"--chip-bg:${bg};--chip-color:${color}\"")
replace('assets/app.js',"function options(){const cats=[...new Set([...categories,...data().map(r=>r.category)])];", "function options(){suggestCustomCategories($('#record-form'),data());const cats=[...new Set([...categories,...data().map(r=>r.category).filter(Boolean)])];")
replace('assets/app.js'," if(r?.category&&!Array.from(form.elements.category.options).some(o=>o.value===r.category))form.elements.category.add(new Option(r.category,r.category));\n for(const k of ['title','date','time','work','category','location','notes'])form.elements[k].value=r?.[k]??(k==='date'?localDate():k==='category'?'部门工作':'');form.elements.people.value=r?r.people.join('、'):'';", " for(const k of ['title','date','time','work','location','notes'])form.elements[k].value=r?.[k]??(k==='date'?localDate():'');form.elements.people.value=r?r.people.join('、'):'';\n setCategoryField(form,r?.category??DEFAULT_CATEGORY);suggestCustomCategories(form,data());")
replace('assets/app.js',"for(const k of ['title','date','time','work','people','category','location','notes'])fields[k]=form.elements[k].value;", "for(const k of ['title','date','time','work','people','location','notes'])fields[k]=form.elements[k].value;\n fields.category=readCategoryField(form);fields.categoryChoice=form.elements.category.value;fields.categoryCustom=form.elements.categoryCustom.value;")
replace('assets/app.js'," dirty=true;renderStaged();$('#form-status').textContent='已恢复暂存的信息与附件，尚未正式保存。';", " setCategoryField($('#record-form'),d.fields?.category??d.category??DEFAULT_CATEGORY,d.fields);\n dirty=true;renderStaged();$('#form-status').textContent='已恢复暂存的信息与附件，尚未正式保存。';")
replace('assets/app.js',"people,category:f.elements.category.value,location:", "people,category:readCategoryField(f),location:")
replace('assets/app.js',"hydrate();\nif(prefs.get('theme')", "hydrate();\n$('#record-form').elements.category.addEventListener('change',()=>updateCategoryVisibility($('#record-form')));\nif(prefs.get('theme')")
replace('assets/app.js','可补充地点、分类、备注，并在右侧多选或拖入附件。','可补充地点、分类、备注，并在右侧多选或拖入附件。活动类型按七项预设选择；选择“其他”可填写自定义名称，留空则保存为“其他”。已有历史分类会保留原名称。')
replace('index.html','<option>部门工作</option><option>会议培训</option><option>志愿服务</option><option>文体活动</option><option>交流分享</option><option>其他</option>', ''.join('<option'+(' selected=""' if x=='部门活动' else '')+'>'+x+'</option>' for x in ['招聘宣讲','线上宣传','经验分享','指导讲座','就业实践','专项活动','部门活动','其他']))
replace('index.html','<select name="category">','<select name="category" aria-controls="category-custom-field" aria-expanded="false">')
replace('index.html','</label></div><label>补充备注', '</label></div><label id="category-custom-field" hidden="">自定义类型名称<input name="categoryCustom" maxlength="50" list="category-custom-names" aria-describedby="category-custom-help" placeholder="例如：校友访谈、企业参访"/><datalist id="category-custom-names"></datalist><small id="category-custom-help">最多 50 个字符；留空则保存为“其他”。保存后可按这个名称查询和筛选。</small></label><label>补充备注')
replace('index.html','<link href="./assets/appearance.css?v=2.2.0"', '<link href="./assets/categories.css?v=2.2.1" rel="stylesheet"/><link href="./assets/appearance.css?v=2.2.0"')
replace('index.html','./assets/boot.js?v=2.2.0','./assets/boot.js?v=2.2.1')
replace('index.html','v2.2.0</span>','v2.2.1</span>')
replace('index.html','v2.2.0 · 双界面共享版','v2.2.1 · 双界面共享版')
replace('assets/boot.js',"'./app.js?v=2.2.0'", "'./app.js?v=2.2.1'")
replace('assets/config.js',"VERSION='2.2.0'","VERSION='2.2.1'")
replace('assets/team-ui.js',"import {team} from './team-client.js?v=2.1.0';", "import {CATEGORY_OPTIONS} from './categories.js?v=2.2.1';\nimport {team} from './team-client.js?v=2.1.0';")
replace('assets/team-ui.js',"'./excel-worker.js?v=2.1.0'", "'./excel-worker.js?v=2.2.1'")
replace('assets/team-ui.js',"category:r.category||'部门工作'", "category:r.category?.trim()||'其他'")
replace('assets/team-ui.js',"const validRow=r=>!!(r.title?.trim()", "const validRow=r=>!!((r.category||'').length<=50&&r.title?.trim()")
replace('assets/team-ui.js','<th>参与具体工作</th><th>人员</th>', '<th>参与具体工作</th><th>人员</th><th>活动类型</th>')
replace('assets/team-ui.js','aria-label="第 ${first+i+1} 条人员"></td></tr>', 'aria-label="第 ${first+i+1} 条人员"></td><td class="category-cell"><input data-row-index="${first+i}" data-field="category" value="${esc(r.category||\'其他\')}" maxlength="50" list="excel-category-names" aria-label="第 ${first+i+1} 条活动类型"></td></tr>')
replace('assets/team-ui.js','<div id="excel-review"></div>','<datalist id="excel-category-names">${CATEGORY_OPTIONS.map(name=>`<option value="${esc(name)}"></option>`).join(\'\')}</datalist><div id="excel-review"></div>')
replace('assets/team-ui.js','无法确定的字段会标记，不自动猜。','无法确定的字段会标记，不自动猜。类型列有值时保留原名；无类型的记录默认“其他”，可在预览中选择预设或输入自定义名称。')
replace('assets/excel-worker.js',"'./excel-core.js?v=2.1.0'", "'./excel-core.js?v=2.2.1'")
replace('assets/excel-core.js',"'工作人员','成员']};", "'工作人员','成员'],category:['活动类型','活动类别','类型','类别','分类']};")
replace('assets/excel-core.js',"category:'部门工作'", "category:text(vals.category)||'其他'")
replace('assets/excel-core.js',"if(Object.keys(found).length>=3)", "if(['title','date','work','people'].filter(k=>found[k]!==undefined).length>=3)")
replace('assets/excel-core.js',"vertical[k]=row[1];if(Object.keys(vertical).length===4)flushVertical(ri+1);continue;", "vertical[k]=row[1];continue;")
replace('assets/excel-core.js',"for(const k of ['title','date','work','people'])vals[k]", "for(const k of ['title','date','work','people','category'])vals[k]")
(p/'package.json').write_text('{"name":"cau-clst-activity-log","version":"2.2.1","private":true,"type":"module","scripts":{"check":"node --check assets/app.js && node --check assets/team-client.js && node --check assets/team-ui.js && node --check assets/store.js && node --check assets/excel-core.js && node --check assets/excel-worker.js && node --check assets/categories.js","test":"node --test tests/*.test.mjs","serve":"python3 -m http.server 8765"}}\n')
replace('tests/ui-modes.py',"'v2.2.0'","'v2.2.1'")
replace('README.md','**v2.2.0 · 双界面、免登录共享版**','**v2.2.1 · 双界面、免登录共享版**')
replace('README.md','## 两套界面，同一份数据','## 活动类型\n\n按顺序提供招聘宣讲、线上宣传、经验分享、指导讲座、就业实践、专项活动、部门活动，以及其他。选择其他后可填写自定义名称（最多 50 个字符）；留空则为其他。自定义名称参与草稿、本机恢复、团队共享、卡片展示、查询、筛选及导出。历史分类不自动改写，编辑时在其他的自定义输入框保留原名。Excel 可识别类型列并在预览中修改；无类型列时默认其他，不自动猜分类。\n\n## 两套界面，同一份数据')
